#!/usr/bin/env bash
# Record the analysis root (directory that contains data/ and output/).
#
# Usage:
#   bash configure_base_dir.sh /path/to/analysis_root
#
# Writes analysis/base_dir.env (gitignored). Scripts read PLM_BASE_DIR from
# the environment or from that file.

set -euo pipefail

PKG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ $# -ne 1 ]]; then
  echo "Usage: bash configure_base_dir.sh /path/to/analysis_root" >&2
  echo "The analysis root is the directory that contains data/ and output/." >&2
  exit 1
fi

if [[ ! -d "$1" ]]; then
  echo "Not a directory: $1" >&2
  exit 1
fi

ANALYSIS_ROOT="$(cd "$1" && pwd)"
ENV_FILE="${PKG_DIR}/analysis/base_dir.env"

cat > "${ENV_FILE}" <<EOF
# Generated by configure_base_dir.sh — local to this machine; not committed.
export PLM_BASE_DIR="${ANALYSIS_ROOT}"
EOF

echo "Wrote ${ENV_FILE#${PKG_DIR}/}"
echo "Analysis root: ${ANALYSIS_ROOT}"
echo ""
echo "For the current shell:"
echo "  export PLM_BASE_DIR=${ANALYSIS_ROOT}"
